import { DEFAULT_SANDBOX_SCENE } from '../sandbox/defaultScene'
import type { Concept, ConceptCategory } from './concept.types'

const sharedDemo = {
  scene: DEFAULT_SANDBOX_SCENE,
  activeObjectId: 'learning-cube',
} as const

export const conceptCategories: readonly ConceptCategory[] = [
  'พื้นฐานโลก 3D',
  'การสร้างวัตถุ',
  'การจัดวาง',
  'การแสดงผล',
]

export const concepts: readonly Concept[] = [
  {
    id: 'coordinate-system',
    order: 1,
    title: 'แกนและพิกัด 3D',
    apiName: 'X · Y · Z',
    category: 'พื้นฐานโลก 3D',
    summary: 'ภาษากลางสำหรับบอกตำแหน่ง ทิศทาง และขนาดในพื้นที่สามมิติ',
    purpose: 'ใช้ระบุว่าวัตถุอยู่ตรงไหน หันไปทางใด และขยายไปตามแกนใด',
    mentalModel: 'นึกถึงห้องหนึ่งห้อง: X คือซ้าย–ขวา, Y คือขึ้น–ลง และ Z คือหน้า–หลัง เส้นแกนสีแดง เขียว และน้ำเงินในฉากช่วยบอกทิศเหล่านี้',
    minimalCode: `cube.position.set(1, 2, -1)`,
    keyPoints: ['X ใช้ซ้าย–ขวา', 'Y ใช้ขึ้น–ลง', 'Z ใช้หน้า–หลัง', 'ค่าต่าง ๆ วัดจากจุดกำเนิด (0, 0, 0)'],
    commonMistakes: ['คิดว่า Z เป็นความสูง ทั้งที่ Three.js ใช้ Y เป็นแกนขึ้นโดยทั่วไป', 'มองทิศบวกและลบผิดเมื่อกล้องเปลี่ยนมุม'],
    relatedConceptIds: ['position', 'rotation', 'scale'],
    officialDocs: 'https://threejs.org/docs/pages/Object3D.html',
    demo: sharedDemo,
  },
  {
    id: 'scene',
    order: 2,
    title: 'พื้นที่รวมของโลก',
    apiName: 'Scene',
    category: 'พื้นฐานโลก 3D',
    summary: 'Container หลักที่เก็บวัตถุ แสง และสิ่งที่ต้องการนำไปแสดงผล',
    purpose: 'รวบรวมองค์ประกอบของโลก 3D ไว้ใน scene graph เดียวเพื่อส่งให้ renderer วาด',
    mentalModel: 'Scene เหมือนเวทีว่าง คุณนำฉาก นักแสดง และไฟเข้ามาวางบนเวที ก่อนเลือกกล้องที่จะใช้ถ่าย',
    minimalCode: `const scene = new THREE.Scene()\nscene.add(cube)`,
    keyPoints: ['สร้างด้วย new THREE.Scene()', 'เพิ่มวัตถุด้วย scene.add()', 'Scene ไม่วาดภาพด้วยตัวเอง'],
    commonMistakes: ['สร้าง Mesh แล้วลืมเพิ่มเข้า Scene', 'คิดว่า Scene เป็น canvas หรือ renderer'],
    relatedConceptIds: ['mesh', 'light', 'webgl-renderer'],
    officialDocs: 'https://threejs.org/docs/pages/Scene.html',
    demo: sharedDemo,
  },
  {
    id: 'perspective-camera',
    order: 3,
    title: 'สายตาของผู้ชม',
    apiName: 'PerspectiveCamera',
    category: 'พื้นฐานโลก 3D',
    summary: 'กล้องแบบมีมิติใกล้–ไกล คล้ายวิธีที่สายตามนุษย์มองโลก',
    purpose: 'กำหนดตำแหน่งและขอบเขตของโลก 3D ที่จะถูกนำมาแสดงบนหน้าจอ',
    mentalModel: 'Scene คือเวที ส่วน Camera คือจุดที่ผู้ชมยืน วัตถุชิ้นเดิมจึงดูต่างกันได้เมื่อกล้องเคลื่อน',
    minimalCode: `const camera = new THREE.PerspectiveCamera(\n  45, width / height, 0.1, 100\n)\ncamera.position.set(4, 3, 5)`,
    keyPoints: ['fov มีหน่วยเป็นองศา', 'aspect มักเท่ากับความกว้างหารความสูง', 'near ต้องมากกว่า 0 และน้อยกว่า far'],
    commonMistakes: ['ย้ายกล้องแล้วไม่ได้หันกลับมาหาวัตถุ', 'คิดว่าการ orbit กล้องเท่ากับแก้ camera.rotation.y อย่างเดียว'],
    relatedConceptIds: ['coordinate-system', 'orbit-controls', 'webgl-renderer'],
    officialDocs: 'https://threejs.org/docs/pages/PerspectiveCamera.html',
    demo: sharedDemo,
  },
  {
    id: 'webgl-renderer',
    order: 4,
    title: 'ผู้วาดภาพลงหน้าจอ',
    apiName: 'WebGLRenderer',
    category: 'การแสดงผล',
    summary: 'ตัววาด Scene จากมุมของ Camera ออกมาเป็นภาพบน canvas',
    purpose: 'เชื่อมโลก Three.js เข้ากับ WebGL และแสดงผลลัพธ์บนหน้าเว็บ',
    mentalModel: 'Renderer เหมือนช่างภาพที่รับทั้งเวทีและกล้อง แล้วบันทึกภาพจากมุมนั้นลงบน canvas',
    minimalCode: `const renderer = new THREE.WebGLRenderer()\nrenderer.setSize(width, height)\nrenderer.render(scene, camera)`,
    keyPoints: ['renderer.domElement คือ canvas ที่นำไปวางในหน้าเว็บ', 'ต้องปรับขนาดเมื่อพื้นที่แสดงผลเปลี่ยน', 'render() ต้องรับทั้ง scene และ camera'],
    commonMistakes: ['สร้าง Renderer แต่ไม่เพิ่ม canvas ลงใน DOM', 'resize canvas แล้วไม่อัปเดต camera.aspect'],
    relatedConceptIds: ['scene', 'perspective-camera', 'animation-loop'],
    officialDocs: 'https://threejs.org/docs/pages/WebGLRenderer.html',
    demo: sharedDemo,
  },
  {
    id: 'geometry',
    order: 5,
    title: 'โครงรูปทรง',
    apiName: 'Geometry',
    category: 'การสร้างวัตถุ',
    summary: 'ข้อมูลรูปทรง เช่น จุด เส้น และพื้นผิวที่บอกว่าวัตถุมีรูปร่างอย่างไร',
    purpose: 'กำหนดโครงสร้างของวัตถุ ก่อนนำไปประกอบกับ Material ให้แสดงผลได้',
    mentalModel: 'Geometry เหมือนโครงกระดาษของโมเดล มันบอกรูปทรงแต่ยังไม่ได้กำหนดสีหรือพื้นผิว',
    minimalCode: `const geometry = new THREE.BoxGeometry(1, 1, 1)`,
    keyPoints: ['BoxGeometry รับความกว้าง ความสูง และความลึก', 'Geometry หนึ่งชุดใช้ร่วมกับหลาย Mesh ได้', 'ควร dispose เมื่อเลิกใช้งาน'],
    commonMistakes: ['คาดว่า Geometry จะแสดงผลได้เอง', 'สร้าง Geometry ใหม่ทุกเฟรมโดยไม่จำเป็น'],
    relatedConceptIds: ['material', 'mesh'],
    officialDocs: 'https://threejs.org/docs/pages/BoxGeometry.html',
    demo: sharedDemo,
  },
  {
    id: 'material',
    order: 6,
    title: 'ลักษณะพื้นผิว',
    apiName: 'MeshStandardMaterial',
    category: 'การสร้างวัตถุ',
    summary: 'กำหนดสี ความด้าน ความเป็นโลหะ และวิธีที่พื้นผิวตอบสนองต่อแสง',
    purpose: 'ทำให้ Geometry มีลักษณะพื้นผิวที่มองเห็นได้และตอบสนองต่อแสงในฉาก',
    mentalModel: 'Geometry คือรูปทรง ส่วน Material คือวัสดุที่นำมาหุ้ม เช่น พลาสติก โลหะ หรือไม้',
    minimalCode: `const material = new THREE.MeshStandardMaterial({\n  color: '#f3a83b',\n  roughness: 0.5\n})`,
    keyPoints: ['MeshStandardMaterial เป็นวัสดุแบบ PBR', 'ต้องมีแสงจึงจะมองเห็นรูปทรงชัด', 'roughness สูงทำให้ผิวดูด้านขึ้น'],
    commonMistakes: ['ใช้วัสดุที่ต้องการแสงในฉากที่ไม่มี Light', 'เปลี่ยนสีผิด object เช่นแก้ Mesh แทน material.color'],
    relatedConceptIds: ['geometry', 'mesh', 'light'],
    officialDocs: 'https://threejs.org/docs/pages/MeshStandardMaterial.html',
    demo: sharedDemo,
  },
  {
    id: 'mesh',
    order: 7,
    title: 'วัตถุที่แสดงผลได้',
    apiName: 'Mesh',
    category: 'การสร้างวัตถุ',
    summary: 'วัตถุที่เกิดจากการนำ Geometry และ Material มาประกอบเข้าด้วยกัน',
    purpose: 'สร้างวัตถุพื้นผิวสามเหลี่ยมที่สามารถเพิ่มเข้า Scene และนำไปแสดงผลได้',
    mentalModel: 'ถ้า Geometry เป็นโครงและ Material เป็นผิว Mesh ก็คือโมเดลที่ประกอบเสร็จพร้อมนำขึ้นเวที',
    minimalCode: `const cube = new THREE.Mesh(geometry, material)\nscene.add(cube)`,
    keyPoints: ['Mesh สืบทอดคุณสมบัติจาก Object3D', 'จึงมี position, rotation และ scale', 'ต้องเพิ่มเข้า Scene หรือ Object3D ตัวอื่น'],
    commonMistakes: ['สลับลำดับ geometry กับ material ใน constructor', 'สร้าง Mesh แล้วลืม scene.add(cube)'],
    relatedConceptIds: ['geometry', 'material', 'scene'],
    officialDocs: 'https://threejs.org/docs/pages/Mesh.html',
    demo: sharedDemo,
  },
  {
    id: 'position',
    order: 8,
    title: 'ตำแหน่งของวัตถุ',
    apiName: 'position',
    category: 'การจัดวาง',
    summary: 'พิกัด X, Y และ Z ของวัตถุเมื่อเทียบกับ parent ของมัน',
    purpose: 'ย้ายวัตถุไปยังตำแหน่งที่ต้องการในพื้นที่สามมิติ',
    mentalModel: 'Position เหมือนการระบุช่องในห้องว่าให้วางกล่องไปทางขวา สูงขึ้น หรือถอยลึกเข้าไปเท่าใด',
    minimalCode: `cube.position.set(1, 0.75, -2)`,
    keyPoints: ['position เป็น Vector3', 'ใช้ .set(x, y, z) หรือแก้ทีละแกนได้', 'ค่าเป็น local position เมื่อวัตถุมี parent'],
    commonMistakes: ['เขียน cube.position = 1 แทนการแก้แกนหรือใช้ set()', 'ลืมว่าพิกัดอาจเป็น local ไม่ใช่ world'],
    relatedConceptIds: ['coordinate-system', 'rotation', 'scale'],
    officialDocs: 'https://threejs.org/docs/pages/Object3D.html',
    demo: sharedDemo,
  },
  {
    id: 'rotation',
    order: 9,
    title: 'การหมุนวัตถุ',
    apiName: 'rotation',
    category: 'การจัดวาง',
    summary: 'การหัน Object3D รอบแกน X, Y และ Z ด้วย Euler angles',
    purpose: 'กำหนดทิศทางที่วัตถุหัน โดยหมุนรอบแกนของตัววัตถุ',
    mentalModel: 'นึกถึงการจับกล่องไว้ที่จุดกึ่งกลาง แล้วหมุนรอบแท่งแกนสีแดง เขียว หรือน้ำเงิน',
    minimalCode: `cube.rotation.y = THREE.MathUtils.degToRad(45)`,
    keyPoints: ['rotation เก็บค่าเป็น radians', 'MathUtils.degToRad() ช่วยแปลงจากองศา', 'การหมุนวัตถุไม่ใช่การ orbit กล้อง'],
    commonMistakes: ['ใส่ 45 ตรง ๆ ทั้งที่ Three.js คาดว่าเป็น radians', 'สับสนระหว่าง cube.rotation กับการลาก OrbitControls'],
    relatedConceptIds: ['coordinate-system', 'position', 'orbit-controls'],
    officialDocs: 'https://threejs.org/docs/pages/Object3D.html',
    demo: sharedDemo,
  },
  {
    id: 'scale',
    order: 10,
    title: 'การย่อและขยาย',
    apiName: 'scale',
    category: 'การจัดวาง',
    summary: 'ตัวคูณขนาดของวัตถุในแต่ละแกน โดยค่าเริ่มต้นคือ 1',
    purpose: 'เปลี่ยนขนาดวัตถุทั้งหมดหรือเฉพาะบางแกนโดยไม่แก้ Geometry เดิม',
    mentalModel: 'Scale เหมือนการยืดหรือบีบโมเดล ค่า 2 คือใหญ่เป็นสองเท่า ส่วน 0.5 คือเหลือครึ่งหนึ่ง',
    minimalCode: `cube.scale.set(1.5, 1, 0.5)`,
    keyPoints: ['ค่าเริ่มต้นคือ (1, 1, 1)', 'ใช้ค่าเท่ากันทุกแกนเพื่อรักษาสัดส่วน', 'ค่า 0 ทำให้วัตถุแบนจนมองไม่เห็นในแกนนั้น'],
    commonMistakes: ['คิดว่าค่าเริ่มต้นคือ 0', 'ใช้ non-uniform scale โดยไม่ตั้งใจจนรูปทรงบิดสัดส่วน'],
    relatedConceptIds: ['coordinate-system', 'position', 'rotation'],
    officialDocs: 'https://threejs.org/docs/pages/Object3D.html',
    demo: sharedDemo,
  },
  {
    id: 'light',
    order: 11,
    title: 'แสงในฉาก',
    apiName: 'Light',
    category: 'การแสดงผล',
    summary: 'แหล่งกำเนิดแสงที่ทำให้ Material บางชนิดแสดงรูปทรงและมิติ',
    purpose: 'กำหนดความสว่าง ทิศทาง และบรรยากาศของวัตถุที่ตอบสนองต่อแสง',
    mentalModel: 'Light เหมือนไฟในสตูดิโอ วัตถุและกล้องอยู่ที่เดิม แต่ภาพเปลี่ยนได้มากตามตำแหน่งและความแรงของไฟ',
    minimalCode: `const light = new THREE.DirectionalLight('#ffffff', 3)\nlight.position.set(4, 6, 3)\nscene.add(light)`,
    keyPoints: ['DirectionalLight มีทิศทางคล้ายแสงอาทิตย์', 'intensity ควบคุมความแรง', 'วัสดุบางชนิดอย่าง MeshBasicMaterial ไม่ต้องใช้แสง'],
    commonMistakes: ['ใช้ MeshStandardMaterial แต่ไม่ได้เพิ่มแสง', 'สร้าง Light แล้วลืมเพิ่มเข้า Scene'],
    relatedConceptIds: ['material', 'scene', 'webgl-renderer'],
    officialDocs: 'https://threejs.org/docs/pages/DirectionalLight.html',
    demo: sharedDemo,
  },
  {
    id: 'animation-loop',
    order: 12,
    title: 'วงรอบการวาดภาพ',
    apiName: 'setAnimationLoop',
    category: 'การแสดงผล',
    summary: 'ฟังก์ชันที่อัปเดตและวาดฉากซ้ำต่อเนื่องเพื่อสร้างการเคลื่อนไหว',
    purpose: 'ทำให้การเปลี่ยนค่า การเคลื่อนไหว และ controls ปรากฏต่อเนื่องบนหน้าจอ',
    mentalModel: 'Animation loop เหมือนสมุดภาพพลิกเร็ว ๆ แต่ละรอบเปลี่ยนสถานะเล็กน้อยแล้ววาดภาพใหม่หนึ่งเฟรม',
    minimalCode: `renderer.setAnimationLoop(() => {\n  cube.rotation.y += 0.01\n  renderer.render(scene, camera)\n})`,
    keyPoints: ['อัปเดต state ก่อน render เฟรมใหม่', 'ใช้ Clock หรือ delta time เมื่อต้องการความเร็วคงที่', 'ต้องหยุด loop เมื่อเลิกใช้ฉาก'],
    commonMistakes: ['สร้าง loop ซ้อนกันหลายชุด', 'ผูกความเร็วกับจำนวนเฟรมโดยไม่คำนึงถึง delta time'],
    relatedConceptIds: ['webgl-renderer', 'rotation', 'orbit-controls'],
    officialDocs: 'https://threejs.org/docs/pages/WebGLRenderer.html',
    demo: sharedDemo,
  },
  {
    id: 'orbit-controls',
    order: 13,
    title: 'หมุนกล้องรอบเป้าหมาย',
    apiName: 'OrbitControls',
    category: 'พื้นฐานโลก 3D',
    summary: 'Addon สำหรับ orbit, zoom และ pan กล้องรอบจุดเป้าหมาย',
    purpose: 'ให้ผู้ใช้สำรวจฉากด้วยเมาส์หรือสัมผัส โดยรักษาทิศขึ้นของกล้องไว้',
    mentalModel: 'กล้องเคลื่อนอยู่บนผิวทรงกลมรอบ target มุมแนวนอนคือ Azimuth ส่วนมุมเงยคือ Elevation',
    minimalCode: `const controls = new OrbitControls(camera, renderer.domElement)\ncontrols.target.set(0, 0.5, 0)\ncontrols.update()`,
    keyPoints: ['ลากซ้ายเพื่อ orbit', 'ล้อเมาส์ใช้ zoom', 'getAzimuthalAngle() คืนค่าแนวนอนเป็น radians', 'เมื่อเปิด damping ต้อง update ใน animation loop'],
    commonMistakes: ['เรียกการลากกล้องว่า rotation ของกล่อง', 'แก้ camera.position แล้วลืม controls.update()'],
    relatedConceptIds: ['perspective-camera', 'coordinate-system', 'animation-loop'],
    officialDocs: 'https://threejs.org/docs/pages/OrbitControls.html',
    demo: sharedDemo,
  },
]

export function getConceptById(id: string | undefined) {
  return concepts.find((concept) => concept.id === id)
}

export function getRelatedConcepts(concept: Concept) {
  return concept.relatedConceptIds
    .map((id) => getConceptById(id))
    .filter((item): item is Concept => Boolean(item))
}
